# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "kubeval-unstable-${version}";
  version = "2018-05-05";
  rev = "6f01a707b19d1033310010c3062ae55976ebd81b";

  goPackagePath = "github.com/garethr/kubeval";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/garethr/kubeval";
    sha256 = "137ws4c77708alm9p3xck4msh93prwypmf38jax5dvrjsa512dz5";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
